<?php
  ini_set('error_reporting', E_ALL);
  ini_set('display_errors', 1);
  ini_set('display_startup_errors', 1);

  require 'libs/phpquery.php';

  $parse_url = 'https://imageshack.com/my/settings';
  $login_url = "https://imageshack.com/rest_api/v2/user/login";
  $username = 'parsertest12@yandex.ru';
  $password = 'Testpassword';
  $cookie_file = "cookie.txt";

  $response = login($login_url, $username, $password, $cookie_file);
  $html = get_page($parse_url, $cookie_file);

  // Get page
  phpQuery::newDocument($html);

  print_r(pq('.username')->html());

  phpQuery::unloadDocuments();

function login($login_url, $username, $password, $cookie_file) {
  // Generated by POSTMAN
  $curl = curl_init();
  curl_setopt_array($curl, array(
    CURLOPT_URL => $login_url,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_COOKIEJAR => $cookie_file,
    CURLOPT_COOKIEFILE => $cookie_file,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "POST",
    CURLOPT_POSTFIELDS => "-----011000010111000001101001\r\nContent-Disposition: form-data; name=\"username\"\r\n\r\n".$username."\r\n-----011000010111000001101001\r\nContent-Disposition: form-data; name=\"password\"\r\n\r\n".$password."\r\n-----011000010111000001101001\r\nContent-Disposition: form-data; name=\"set_cookies\"\r\n\r\ntrue\r\n-----011000010111000001101001--",
    CURLOPT_HTTPHEADER => array(
      "cache-control: no-cache",
      "content-type: multipart/form-data; boundary=---011000010111000001101001",
      "postman-token: 0c8e6d81-3db4-a014-4c98-6f6a6ef1de10"
    ),
  ));

  $response = curl_exec($curl);
  $err = curl_error($curl);
// if ($err) {
//   echo "cURL Error #:" . $err;
// } else {
//   echo $response;
// }
  curl_close($curl);

  return $response;
}

function get_page($parse_url, $cookie_file) {
  $curl = curl_init($parse_url);
  curl_setopt($curl, CURLOPT_URL, $parse_url );
  //curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
  curl_setopt($curl, CURLOPT_POST, false);
  curl_setopt($curl, CURLOPT_FOLLOWLOCATION, 1);
  curl_setopt($curl, CURLOPT_COOKIEFILE, $cookie_file);
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);

  $html = curl_exec($curl);
  curl_close($curl);

  return $html;
}

?>